### ISSUE TITLE
segfault when changing bottoms of a SoftmaxWithLoss layer

### ISSUE THREAD

**Issue by jacobandreas** [Russell91/apollocaffe#12]
```python
import caffe
from apollocaffe import ApolloNet, layers
import numpy as np

net = ApolloNet()

net.clear_forward()
net.f(layers.NumpyData("input", data=np.random.random((256, 8, 20, 20))))
net.f(layers.NumpyData("target", data=np.random.randint(32, size=(256,))))
net.f(layers.InnerProduct("ip1", 32, bottoms=["input"]))
net.f(layers.SoftmaxWithLoss("loss", bottoms=["ip1", "target"]))
net.backward()
print "done1"

net.clear_forward()
net.f(layers.NumpyData("input", data=np.random.random((256, 8, 20, 20))))
net.f(layers.NumpyData("target", data=np.random.randint(32, size=(256,))))
net.f(layers.InnerProduct("ip2", 32, bottoms=["input"]))
net.f(layers.SoftmaxWithLoss("loss", bottoms=["ip2", "target"]))
net.backward()
print "done2"
```

```
done1
./run.sh: line 9: 22031 Segmentation fault      (core dumped) python bug.py
```

Problem goes away if you change the second loss to "loss2", so easy to work around, but a bit surprising.

**Comment by Russell91** [comment]
Thanks Jacob, you've found a bug! The fix is now pushed to the dev branch here: https://github.com/Russell91/apollocaffe/commit/ec923edcad1998cc52cc886676bf9bc03ccdee6b

Apollocaffe should never throw a segfault. This type of program is indeed supposed to be supported by Apollocaffe. When the user passes new bottoms to an old layer, we swap out those pointers and pass them into the Forward_cpu/gpu() call for the layer. In this case though, the softmax_with_loss layer was making an implicit (and unnecessary) assumption that it could cache the first bottom[0] it saw into a member variable. Simply updating this cache at every forward pass fixes the problem.
