### ISSUE TITLE
how to continue to train the net using apollocaffe python wrapper

### ISSUE THREAD

**Issue by terrychenism** [Russell91/apollocaffe#13]
Hi, Russell,

Your apollocaffe python wrapper can accept weights as input to finetune the net, I wanna ask how to continue to train net using apollocaffe python wrapper?  Thanks.

**Comment by Russell91** [comment]
The recommended method for restarting from saved weights is to pass e.g. --weights weights_10000.h5 --start_iter 10000. This just starts the for loop at 10000 rather than 0, and works quite well.

We found that the original .solverstate .caffemodel duo was just too complicated given that it adds little more than the above trick. Sure, it's no longer possible to load momentum terms and continue exactly as if you hadn't stopped the process - but if you truly cared about that, you could have just not stopped the process.

**Comment by terrychenism** [comment]
Got it. Thanks a lot!
